huodongtong/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to:'users#login'
  match '/signup', to: 'users#signup', via: 'get'
  match '/welcome', to: 'users#welcome', via: 'get'
  post '/create_login_session',to:'users#create_login_session'
  delete'logout',to:'users#logout',:as =>'logout'
  get 'manager_index',to:'users#manager_index',:as => 'manager_index'
  match '/add_user',to:'users#add_user',via:'get'
  delete '/delete_user',to:'users#delete_user',:as =>'delete_user'
  get '/change_password',to:'users#change_password',:as=>'change_password'
  post '/change_password_action',to:'users#change_password_action'
  get '/forget_one',to:'users#forget_one', :as => 'forget_one'
  post '/next_one',to:'users#next_one'
  get '/forget_two',to:'users#forget_two', :as => 'forget_two'
  post '/next_two',to:'users#next_two'
  get '/forget_three',to:'users#forget_three', :as => 'forget_three'
  post '/next_three',to:'users#next_three'
  post '/get_http_user_log',to:'users#get_http_user_log'
  post'/upload',to:'users#upload'
  get '/user_index',to:'users#user_index',:as=>'user_index'
  get'/bid_list',to:'users#bid_list',:as=>'bid_list'
  get '/baoming',to:'users#baoming',:as=>'baoming'
  get '/bid_details',to:'users#bid_details',:as=>'bid_details'
  get '/price_count',to:'users#price_count',:as=>'price_count'
  get '/tongbu_show',to:'users#tongbu_show',:as=>'tongbu_show'
  post '/upload_bid_details',to:'users#upload_bid_details'
  get '/show_over',to:'users#show_over'

end

huodongtong/app/models/user.rb
class User < ActiveRecord::Base
  before_create{ generate_token(:token)}
  validates :name, :presence=> true,uniqueness: {:case_sensitive => false}
  validates :password,:presence => true, :on => :create
  has_secure_password
  validates :forget_password_question,presence: true
  validates :forget_password_answer,presence: true
  def generate_token(column)
    begin
      self[column]=SecureRandom.urlsafe_base64
    end while User.exists?(column=>self[column])
  end

end

huodongtong/app/controllers/users_controller.rb
#encoding:utf-8
class UsersController < ApplicationController
  protect_from_forgery with: :null_session, if: Proc.new { |c| c.request.format == 'application/json' }

  def welcome
  end

  def signup
    @user=User.new
  end

  def login
    create_admin
    if current_admin
      redirect_to :manager_index
    else
      if current_user
        redirect_to :user_index
      end
    end
  end

  def create_login_session
    user=User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      if user.role=='Ordinary_user'
        cookies.permanent[:token]=user.token
        redirect_to :user_index
      else
        if user.role=='admin'
          cookies.permanent[:token_admin]=user.token
          redirect_to :manager_index
        end
      end
    else
      flash[:error]="用户不存在或密码错误"
      redirect_to :root
    end
  end

  def logout
    if current_admin
      if current_user
        cookies.delete(:token_admin)
        cookies.delete(:token)
      else
        cookies.delete(:token_admin)
      end
    end
    if current_user && !current_admin
      cookies.delete(:token)
    end
    flash[:error].display
    redirect_to root_url
  end

  def create
    if current_admin
      @user=User.new(user_params)
      if @user.save
        redirect_to :add_user
      else
        render :add_user
      end
    else
      @user=User.new(user_params)
      if @user.save
        cookies.permanent[:token]=@user.token
        redirect_to :user_index
      else
        render :signup
      end
    end
  end

  def create_admin
    if User.any?
    else
      @user=User.new(:name => 'admin', :password => 'admin', :password_confirmation => 'admin', :forget_password_question => 'admin', :forget_password_answer => 'admin', :role => 'admin')
      @user.save
    end
  end

  def manager_index
    if current_user
      cookies.delete(:token)
    end
    session[:result]=''
    if current_admin
      user=User.where(:role => 'Ordinary_user')
      @user=user.paginate(page: params[:page], per_page: 10)
      if params[:page].to_i==0
        @page_index=1
      else
        @page_index=params[:page].to_i
      end
    else
      redirect_to :root
    end
  end

  def add_user
    if current_admin
      @user=User.new
    else
      redirect_to :root
    end
  end

  def delete_user
    if current_admin
      User.find_by_name(params[:name]).delete
      redirect_to :manager_index
    else
      redirect_to :root
    end
  end

  def change_password_action
    session[:result]=""
    user=User.find_by_name(session[:name])
    if params[:password]==params[:password_confirmation] && params[:password]!=""
      user.password=params[:password]
      user.password_confirmation=params[:password_confirmation]
      user.save
      @result='success'
      session[:result]= @result
      flash[:error].display
      redirect_to :change_password
    else
      if params[:password]==""|| params[:password_confirmation]==""
        flash[:error]="密码或确认密码不能为空！"
        render :change_password
      else
        flash[:error]="两次密码输入不一致，请重新输入！"
        render :change_password
      end
    end

  end

  def change_password
    if current_admin
      session[:name]=params[:name]
    else
      redirect_to :root
    end
  end

  def forget_one

  end

  def next_one
    user=User.find_by_name(params[:name])
    if user
      session[:name]=user.name
      session[:forget_password_question]=user.forget_password_question
      session[:forget_password_answer]=user.forget_password_answer
      redirect_to :forget_two
    else
      if params[:name]==""
        flash[:error]="帐号不能为空"
        redirect_to :forget_one
      else
        flash[:error]="该帐号不存在"
        redirect_to :forget_one
      end
    end
  end

  def forget_two

  end

  def next_two
    if session[:forget_password_answer]==params[:answer]
      redirect_to :forget_three
    else
      flash[:error]="忘记密码答案错误"
      redirect_to :forget_two
    end
  end

  def forget_three

  end

  def next_three
    if params[:password]==params[:password_confirmation]&&params[:password]!=""
      user=User.find_by_name(session[:name])
      user.password=params[:password]
      user.password_confirmation=params[:password_confirmation]
      if user.save
        if user.role=='admin'
          cookies.permanent[:token_admin]=user.token
          redirect_to :manager_index
        else
          if user.role=='Ordinary_user'
            cookies.permanent[:token]=user.token
            redirect_to :user_index
          end
        end
      end
    else
      if params[:password]==""||params[:password_confirmation]==""
        flash[:error]="密码或确认密码不能为空"
        render :forget_three
      else
        if params[:password]!=params[:password_confirmation]
          flash[:error]="两次密码输入不一致，请重新输入"
          render :forget_three
        end
      end
    end
  end

  def get_http_user_log
    user=User.find_by_name(params[:name])
    respond_to do |format|
      if user && user.authenticate(params[:password])
        format.json { render json: {data: 'true'} }
      else
        format.json { render json: {data: 'false'} }
      end
    end
  end

  def upload
    @currentlogUser=params[:currentlogUser]
    @current_activity=params[:current_activity]
    @current_bid=params[:current_bid]
    @post_user_activity_message=params[:post_user_activity_message]
    @post_bid_list_infos=params[:post_bid_list_infos]
    @post_bm_infos=params[:post_bm_infos]
    @post_bid_details=params[:post_bid_details]
    @post_bid_success=params[:post_bid_success]
    @post_bid_price_group=params[:post_bid_price_group]
    result1=UserActivityMessageInfo.show_user_info(@currentlogUser, @post_user_activity_message)
    result2=BidListInfos.show_bid_list_info(@currentlogUser, @post_bid_list_infos, @current_activity)
    result3=BmInfo.show_bm_infos(@currentlogUser, @post_bm_infos)
    result4=BidDetail.show_bid_details(@currentlogUser, @post_bid_details)
    result5=BidSuccessDetail.show_bid_success_details(@currentlogUser, @post_bid_success)
    result6=BidPriceGroupDetail.show_bid_price_group_details(@currentlogUser, @post_bid_price_group)
    result7=CurrentUserActivity.store_current_activity(@currentlogUser, @current_activity, @current_bid)
    respond_to do |format|
      if result1=='true'&& result2=='true'&& result3=='true'&&result4=='true'&& result5=="true" && result6=='true' &&result7=='true'
        format.json { render json: {data: 'true'} }
      else
        format.json { render json: {data: 'false'} }
      end
    end
  end

  def user_index
    if current_admin && !current_user
      @user=User.find_by_name(params[:username])
      cookies.permanent[:token]=@user.token
    end
    if current_user
      user_activity_message_info=UserActivityMessageInfo.where(username: current_user.name)
      @user_activity_message_info=user_activity_message_info.paginate(page: params[:page], per_page: 10)
      if params[:page].to_i==0
        @page_index=1
      else
        @page_index=params[:page].to_i
      end
      @current_activity_user=CurrentUserActivity.find_by_username(current_user.name)
      @current_activity_name=@current_activity_user.activity_name
      @bid_details=BidDetail.where(username: current_user.name, activity_name: @current_activity_name, status: 'true')
      if @bid_details==[]
        @start="false"
      else
        @start="true"
      end
    else
      redirect_to :root
    end
  end

  def bid_list
    if current_user
      session[:activity_name]=params[:activity_name]
      bid_list_infos=BidListInfos.where(username: current_user.name, activity_name: session[:activity_name])
      @bid_list_infos=bid_list_infos.paginate(page: params[:page], per_page: 10)
      if params[:page].to_i==0
        @page_index=1
      else
        @page_index=params[:page].to_i
      end
    end
  end

  def baoming
    if current_user
      session[:activity_name]=params[:activity_name]
      bm_infos=BmInfo.where(username: current_user.name, activity_name: params[:activity_name])
      @bm_infos=bm_infos.paginate(page: params[:page], per_page: 10)
      if params[:page].to_i==0
        @page_index=1
      else
        @page_index=params[:page].to_i
      end
    end
  end

  def bid_details
    session[:bid_name]=params[:bid_name]
    @activity_name=params[:activity_name]
    @bid_name=params[:bid_name]
    @bid_detailss=BidDetail.where(username: current_user.name, activity_name: @activity_name, bid_name: @bid_name)
    @bid_details=@bid_detailss.paginate(page: params[:page], per_page: 10)
    @bid_details.each do |bid_detail|
      @bid_status=bid_detail.status
      @bid_person_name=bid_detail.person_name
    end
    if params[:page].to_i==0
      @page_index=1
    else
      @page_index=params[:page].to_i
    end
    @bid_success_details=BidSuccessDetail.where(username: current_user.name, activity_name: @activity_name, bid_name: @bid_name)
    @bid_success_details.each do |bid_success_detail|
      @bid_success_detail=bid_success_detail
      @person_name=@bid_success_detail.person_name
      @success_price=@bid_success_detail.success_price
      @phone_number=@bid_success_detail.phone_number
      if @person_name==""
        @success="false"
      else
        @success="true"
      end
    end
  end

  def price_count
    @person_name=params[:person_name]
    @success_price=params[:success_price]
    @phone_number=params[:phone_number]
    @activity_name=params[:activity_name]
    @bid_name=params[:bid_name]
    price_group_details=BidPriceGroupDetail.where(username: current_user.name, activity_name: @activity_name, bid_name: @bid_name)
    @price_group_detailss=price_group_details.paginate(page: params[:page], per_page: 10)
    if @person_name==""||@person_name==nil
      @success="false"
    else
      @success="true"
    end
    @bid_details=BidDetail.where(username: current_user.name, activity_name: @activity_name, bid_name: @bid_name)

huodongtong/app/helpers/users_helper.rb
module UsersHelper
end

huodongtong/app/views/users/add_user.haml
%ol.breadcrumb.breadtitle
  %li
    %a{:href => manager_index_path} 首页
  %li.active 添加用户
.single-form-container
  .well.well-lg.backpanel
    = form_for @user do |f|
      %br
        .input-group
          = f.label :帐号, class: "input-group-addon ", :style => "padding-left: 50px;padding-right: 50px"
          = f.text_field :name, class: " form-control "
      %br
        .input-group
          = f.label :请设置密码, class: "input-group-addon", :style => "padding-left: 30px;padding-right: 30px"
          = f.password_field :password, class: "form-control"
      %br
        .input-group
          = f.label :请确认密码, class: " input-group-addon", :style => "padding-left: 30px;padding-right: 30px"
          = f.password_field :password_confirmation, class: "form-control"
      %br
        .input-group
          = f.label :忘记密码问题, class: " input-group-addon", :style => "padding-left: 24px;padding-right: 24px"
          = f.text_field :forget_password_question, class: "form-control"
      %br
        .input-group
          = f.label :忘记密码答案, class: " input-group-addon", :style => "padding-left: 24px;padding-right: 24px"
          = f.text_field :forget_password_answer, class: "form-control"
      %br
        #{@user.errors}
        - if @user.errors.any?
          .alert.alert-danger.alert-style
            = @user.errors.full_messages.first
      %p
        = f.submit "确认添加", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/bid_details.haml
%ol.breadcrumb.breadtitle
  %li
    %a{:href => user_index_path} 首页
  %li
    %a
    = link_to "竞价列表",bid_list_path(:activity_name=>@activity_name)
  %li.active
    = session[:bid_name]
.single-form-container
  .well.well-lg.backpanel_success_message
    - if @success=="true"
      %h4.center_success
        获胜者:
        = @person_name
      %h4.center_success
        出价：
        = @success_price
        元
      %h4.center_success
        手机号：
        = @phone_number
    - if @success=="false"
      %h4.center_success
        本次竞价无人胜出
    - if @bid_status=="true"
      %h4.center_success
        活动正在进行中...
.bid-detail-box
  %table.table
    %thead
      %ul.nav.nav-tabs.nav-justified
        %li.active.bidcenter
          %a
            出价列表
        %li
          =link_to '价格统计',price_count_path(:person_name=>@person_name,:success_price=>@success_price,:phone_number=>@phone_number,:activity_name=>@activity_name,:bid_name=>@bid_name)
      %td(align="center")  编号
      %td(align="center")  姓名
      %td(align="center")  价格/元
      %td(align="center")  手机号
    %tbody
      -if @bid_person_name!=""
        - id=(@page_index-1)*10
        - @bid_details.each do |bid_detail|
          %tr
            %td(align="center")= id=id+1
            %td(align="center")= bid_detail.person_name
            %td(align="center")= bid_detail.bid_price
            %td(align="center")= bid_detail.phone_number
  .paginate.pagestyle
    = will_paginate @bid_details, :previous_label=>'<<',:next_label=>'>>'

huodongtong/app/views/users/bid_list.haml
%ol.breadcrumb.breadtitle
  %li
    %a{:href => user_index_path} 首页
  %li.active 竞价列表
.single-form-container
  .well.well-lg.panel_heading
    .manager-index-header
      竞价列表 &nbsp&nbsp&nbsp
      .baominglinkstyle= link_to "报名列表",baoming_path(:activity_name=>session[:activity_name])
  %table.table.panel-first-row.table-bordered
    %tr
      %td(align="center")  编号
      %td(align="center")  名称
      %td(align="center")  参与人数
    - id=(@page_index-1)*10
    - @bid_list_infos.each do |bid_list_info|
      %tr
        %td(align="center")= id=id+1
        %td(align="center")= link_to bid_list_info.bid_name, bid_details_path(:activity_name=>session[:activity_name],:bid_name=>bid_list_info.bid_name)
        %td(align="center")= bid_list_info.bid_message_no+"/"+bid_list_info.bm_no
  .paginate.pagestyle
    = will_paginate @bid_list_infos, :previous_label=>'<<',:next_label=>'>>'

huodongtong/app/views/users/change_password.haml
%ol.breadcrumb.breadtitle
  %li
    %a{:href => manager_index_path} 首页
  %li.active 修改用户密码
.single-form-container
  .well.well-lg.backpanel
    = form_tag '/change_password_action' do
      .input-group
        .input-group-addon.login_label
          = label_tag :帐号
        = label_tag :name, session[:name],:disabled=>'disabled',class: " form-control "
      %br
        .input-group
          .input-group-addon.cahngepassword_label
            = label_tag "请设置密码"
          = password_field_tag :password, params[:password], class: " form-control ", :placeholder=>"请输入新密码"
      %br
        .input-group
          .input-group-addon.cahngepassword_label
            = label_tag :请确认密码
          = password_field_tag :password_confirmation, params[:password_confirmation],class: "form-control",:placeholder=>"请再次输入"
      %br
        - if flash[:error]
          .alert.alert-danger.flash_center
            =flash[:error]
        -if session[:result]=="success"
          #alert.modal
            .modal-dialog
              .modal-content
                .modal-header
                  %h2.modal-title
                    .modal-body.text-center
                      %h2 修改成功
                .modal-footer
                  = link_to "确定", manager_index_path, :class => "btn btn-default"

          :javascript
            $('#alert').modal('show')
      %p
        = submit_tag "确认修改", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/forget_three.haml
.single-form-container
  .well.well-lg.backpanel
    .register 重置密码
    .login_user
      = link_to "用户登录", root_path
    %br
    = form_tag '/next_three' do
      .input-group
        .input-group-addon.login_label
          = label_tag "请设置密码"
        = password_field_tag :password, params[:password], class: " form-control ",:placeholder=>'请输入新密码'
      %br
        .input-group
          .input-group-addon.login_label
            = label_tag "请确认密码"
          = password_field_tag :password_confirmation, params[:password_confirmation], class: " form-control ",:placeholder=>'请再次输入'
      %br
        - if flash[:error]
          .alert.alert-danger.flash_center
            =flash[:error]
      %p
        = submit_tag "确认修改", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/forget_two.haml
.single-form-container
  .well.well-lg.backpanel
    .register 重置密码
    .login_user
      = link_to "用户登录", root_path
    %br
    = form_tag '/next_two' do
      .input-group
        .input-group-addon.login_label
          = label_tag "忘记密码问题"
        = text_field_tag :name, session[:forget_password_question], class: " form-control ",:disabled=>'disabled'
      %br
        .input-group
          .input-group-addon.login_label
            = label_tag "忘记密码答案"
          = text_field_tag :answer, params[:answer], class: " form-control ",:placeholder=>'请输入答案'
      %br
        - if flash[:error]
          .alert.alert-danger.flash_center
            =flash[:error]
      %p
        = submit_tag "下一步", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/login.haml
.single-form-container
  .well.well-lg.backpanel
    .register 用户登录
    .login_user
      = link_to "用户注册", signup_path
    %br
    = form_tag '/create_login_session' do
      .input-group
        .input-group-addon.login_label
          = label_tag "帐号"
        = text_field_tag :name, params[:name], class: " form-control "
      %br
      .input-group
        .input-group-addon.login_label
          = label_tag "密码"
        = password_field_tag :password, params[:password], class: " form-control "
      %br
        -flash.each do |key, value|
          .alert.alert-danger.alert-style
            %div{:class => "alert-#{key}"}= value
        .login_user
          = link_to "忘记密码",forget_one_path
      %br
      %p
        = submit_tag "登录", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/login.html.erb
<div class="single-form-container">
  <div class="well well-lg backpanel">
    <div class="register">用户登录</div>
    <div class="login_user">
      <%= link_to "用户注册", signup_path %>
    </div>
    <br>
    <%= form_tag '/create_login_session' do %>
        <div class="input-group">
          <div class=" input-group-addon login_label">
            <%= label_tag "帐号" %>
          </div>
          <%= text_field_tag :name, params[:name], class: " form-control " %>
        </div>
        <br>

        <div class="input-group ">
          <div class=" input-group-addon login_label">
            <%= label_tag "密码" %>
          </div>
          <%= password_field_tag :password, params[:password], class: " form-control " %>
        </div>
        <br>
        <% flash.each do |key, value| %>
            <div class="alert alert-danger alert-style">
            <div class="alert-<%= key %>"><%= value %></div>
            </div>
        <% end %>
        <div class="login_user">
          <%= link_to "忘记密码" %>
        </div>
        <br>
        <p><%= submit_tag "登录", class: "btn btn-large btn-primary sign_up_button" %>
    <% end %>
  </div>
</div>

huodongtong/app/views/users/manager_index.haml
.single-form-container
  .well.well-lg.panel_heading
    .manager-index-header
      用户管理 &nbsp&nbsp&nbsp
      = link_to "+添加用户", add_user_path,:class=>"btn btn-default"
  %table.table.panel-first-row.table-bordered
    %tr
      %td(align="center")  编号
      %td(align="center")  用户名
      %td(align="center")   操作
    - id=(@page_index-1)*10
    - @user.each do |user|
      %tr
        %td(align="center")= id=id+1
        %td(align="center")= link_to user.name,user_index_path(:username=>user.name)
        %td(align="center")
          = link_to "删除" ,delete_user_path(:name=>user[:name]),data:{ :confirm =>'您确定要删除'+user.name+'?'} , :method=>:delete
          = link_to "修改密码",change_password_path(:name=>user[:name])
  .paginate.pagestyle
    = will_paginate @user, :previous_label=>'<<',:next_label=>'>>'

huodongtong/app/views/users/price_count.haml
%ol.breadcrumb.breadtitle
  %li
    %a{:href => user_index_path} 首页
  %li
    %a
      = link_to "竞价列表",bid_list_path(:activity_name=>@activity_name)
  %li.active
    = session[:bid_name]
.single-form-container
  .well.well-lg.backpanel_success_message
    - if @success=="true"
      %h4.center_success
        获胜者:
        = @person_name
      %h4.center_success
        出价：
        = @success_price
        元
      %h4.center_success
        手机号：
        = @phone_number
    - if @success=="false"&&@bid_status=="false"
      %h4.center_success
        本次竞价无人胜出
    - if @bid_status=="true"
      %h4.center_success
        活动正在进行中...
.bid-detail-box
  %table.table
    %thead
      %ul.nav.nav-tabs.nav-justified
        %li.bidcenter
          =link_to '出价列表',bid_details_path(:person_name=>@person_name,:success_price=>@success_price,:phone_number=>@phone_number,:activity_name=>@activity_name,:bid_name=>@bid_name)
        %li.active
          %a
            价格统计
      %td(align="center")  价格/元
      %td(align="center")  人数
    %tbody
      - @price_group_detailss.each do |price_group_detail|
        %tr
          %td(align="center")= price_group_detail.price
          %td(align="center")= price_group_detail.count
  .paginate.pagestyle
    = will_paginate @price_group_detailss, :previous_label=>'<<',:next_label=>'>>'

huodongtong/app/views/users/signup.haml
.single-form-container
  .well.well-lg.backpanel
    = form_for @user do |f|
      .register 新用户注册
      .login_user
        = link_to "用户登录", root_path
      %br
      .input-group
        = f.label :帐号, class: "input-group-addon ", :style => "padding-left: 50px;padding-right: 50px"
        = f.text_field :name, class: " form-control "
      %br
      .input-group
        = f.label :请设置密码, class: "input-group-addon", :style => "padding-left: 30px;padding-right: 30px"
        = f.password_field :password, class: "form-control"
      %br
      .input-group
        = f.label :请确认密码, class: " input-group-addon", :style => "padding-left: 30px;padding-right: 30px"
        = f.password_field :password_confirmation, class: "form-control"
      %br
      .input-group
        = f.label :忘记密码问题, class: " input-group-addon", :style => "padding-left: 24px;padding-right: 24px"
        = f.text_field :forget_password_question, class: "form-control"
      %br
      .input-group
        = f.label :忘记密码答案, class: " input-group-addon", :style => "padding-left: 24px;padding-right: 24px"
        = f.text_field :forget_password_answer, class: "form-control"
      %br
        - if @user.errors.any?
          .alert.alert-danger.alert-style
            = @user.errors.full_messages.first
        %p
          = f.submit "注册", class: "btn btn-large btn-primary sign_up_button"

huodongtong/app/views/users/tongbu_show.haml
.single-form-container
   .well.well-lg.backpanel_success_message
      -if @tongbu=="true"
         %h3.center_success
            =@current_activity_name
         %h3.center_success
            参与人数：
            =@num_result
%table.table.panel-first-row.table-bordered
   %tr
      %td(align="center")  姓名
      %td(align="center")  电话
   - @bid.each do |bid_details|
      %tr
      %td(align="center")=bid_details.person_name
      %td(align="center")=bid_details.phone_number[0]+bid_details.phone_number[1]+bid_details.phone_number[2]+bid_details.phone_number[3]+"XXX"+bid_details.phone_number[7]+bid_details.phone_number[8]+bid_details.phone_number[9]+bid_details.phone_number[10]
%script{:language => "JavaScript"}
   function myrefresh() {
   window.location.reload();
   }
   setTimeout('myrefresh()',3000);

huodongtong/app/views/users/user_index.haml
.single-form-container
  .well.well-lg.panel_heading
    .manager-index-header
      活动信息
      -if @start=="true"
        = link_to "同步展示",tongbu_show_path,:class=>"btn btn-default tongbushow_button"
      -if @start=="false"
        = link_to "同步展示",user_index_path,:class=>"btn btn-default tongbushow_button"
  %table.table.panel-first-row.table-bordered
    %tr
      %td(align="center")  编号
      %td(align="center")  活动名称
      %td(align="center")  报名人数
      %td(align="center")  竞价次数
    - id=(@page_index-1)*10
    - @user_activity_message_info.each do |activity_message|
      %tr
        %td(align="center")= id=id+1
        %td(align="center")= link_to activity_message.activity_name ,bid_list_path(:activity_name=>activity_message.activity_name)
        %td(align="center")= link_to activity_message.bm_no,baoming_path(:activity_name=>activity_message.activity_name)
        %td(align="center")= link_to activity_message.bid_no,bid_list_path(:activity_name=>activity_message.activity_name)
  .paginate.pagestyle
    = will_paginate @user_activity_message_info, :previous_label=>'<<',:next_label=>'>>'

huodongtong/app/views/users/welcome.haml
.container
  %h1.welcome Welcome