huodongtong/config/routes.rb
Rails.application.routes.draw do
  resources :users
  root to:'users#login'
  match '/signup', to: 'users#signup', via: 'get'
  match '/welcome', to: 'users#welcome', via: 'get'
  post '/create_login_session',to:'users#create_login_session'
  delete'logout',to:'users#logout',:as =>'logout'
  get 'manager_index',to:'users#manager_index',:as => 'manager_index'
  match '/add_user',to:'users#add_user',via:'get'
  delete '/delete_user',to:'users#delete_user',:as =>'delete_user'
  get '/change_password',to:'users#change_password',:as=>'change_password'
  post '/change_password_action',to:'users#change_password_action'
  get '/forget_one',to:'users#forget_one', :as => 'forget_one'
  post '/next_one',to:'users#next_one'
  get '/forget_two',to:'users#forget_two', :as => 'forget_two'
  post '/next_two',to:'users#next_two'
  get '/forget_three',to:'users#forget_three', :as => 'forget_three'
  post '/next_three',to:'users#next_three'
  post '/get_http_user_log',to:'users#get_http_user_log'
  post'/upload',to:'users#upload'
  get '/user_index',to:'users#user_index',:as=>'user_index'
  get'/bid_list',to:'users#bid_list',:as=>'bid_list'
  get '/baoming',to:'users#baoming',:as=>'baoming'
  get '/bid_details',to:'users#bid_details',:as=>'bid_details'
  get '/price_count',to:'users#price_count',:as=>'price_count'
  get '/tongbu_show',to:'users#tongbu_show',:as=>'tongbu_show'
  post '/upload_bid_details',to:'users#upload_bid_details'
  get '/show_over',to:'users#show_over'

end

huodongtong/app/views/shared/_flash_message.html.erb
<% if flash[:notice]%>
    <div class="flash-notice">
        <%=flash[:notice]%>
    </div>
<% end %>
<%if flash[:alert]%>
    <div class="flash-alert">
      <%=flash[:alert]%>
    </div>
<% end %>
<% if flash[:error]%>
    <div class="flash-error">
      <%=flash[:error]%>
    </div>
<% end %>

huodongtong/app/views/shared/_header.haml
.navbar.navbar-default.navbar-fixed-top
  .container
    = link_to "活动通", '#', id: "logo"
    %nav
      %ul.tna.nav.pull-right
        -if current_user||current_admin
          .login_title
            你好，
            -if current_admin
              管理员
              \#{link_to "退出", logout_path, method: 'delete', class: 'logout_title'}
            -if current_user
              \#{p current_user.name}
              =link_to '退出',manager_index_path

huodongtong/app/views/shared/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <%= link_to "活动通", '#', id: "logo" %>
    <nav>
      <ul class=" tna nav pull-right ">
        <% if current_user %>
            <div class="login_title">你好，
              <%= p current_user.name %>
              <%= link_to "退出", logout_path, method: 'delete', class: 'logout_title'%>
            </div>
        <% else %>

        <% end %>
      </ul>
    </nav>
  </div>
</div>